name: capstone
description: "Capstone Project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI and utilities
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.3

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.4.10
  cloud_functions: ^5.1.1
  pdf: ^3.10.1
  printing: ^5.11.0

  # File picking (auto supports desktop now)
  file_picker: ^8.0.5

  #for violation per barangay
  fl_chart: ^0.68.0

  # Media
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
